/*
 * This file is generated by jOOQ.
 */
package ee.rabi.ali.api.account.orm.model;


import ee.rabi.ali.api.account.orm.model.tables.Account;
import ee.rabi.ali.api.account.orm.model.tables.Ledger;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LEDGER_ACCOUNT_ID_FK_INDEX_E = Indexes0.LEDGER_ACCOUNT_ID_FK_INDEX_E;
    public static final Index LEDGER_ACCOUNT_ID_FK_INDEX_8 = Indexes0.LEDGER_ACCOUNT_ID_FK_INDEX_8;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LEDGER_ACCOUNT_ID_FK_INDEX_E = Internal.createIndex("LEDGER_ACCOUNT_ID_FK_INDEX_E", Account.ACCOUNT, new OrderField[]{Account.ACCOUNT.ID}, true);
        public static Index LEDGER_ACCOUNT_ID_FK_INDEX_8 = Internal.createIndex("LEDGER_ACCOUNT_ID_FK_INDEX_8", Ledger.LEDGER, new OrderField[]{Ledger.LEDGER.ACCOUNT_ID}, false);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Ledger.LEDGER, new OrderField[]{Ledger.LEDGER.ID}, true);
    }
}
